### ISSUE TITLE
python example does not work as headers are not set in client.__http_request()

### ISSUE THREAD

**Issue by gireeshramji** [pilosa/getting-started#15]
Hi I ran into trouble running the getting started example because of the following:

Calling client.status() failed with the following error:

```
>>> client.status()
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/Users/gireeshramji/PycharmProjects/getting-started/python/venv/lib/python2.7/site-packages/pilosa/client.py", line 188, in status
    client_response=Client.__ERROR_CHECKED_RESPONSE)
  File "/Users/gireeshramji/PycharmProjects/getting-started/python/venv/lib/python2.7/site-packages/pilosa/client.py", line 320, in __http_request
    raise PilosaError("Server error (%d): %s" % (response.status, content))
PilosaError: Server error (406): JSON only acceptable response
```

Calling client._Client__client.request without headers also fails:

```
r = client._Client__client.request("GET",uri)
r.status
406
```

Calling client._Client__client.request with 'Accept':'application/json' succeeds

```
r = client._Client__client.request("GET",uri,headers = {'Accept':'application/json'})
r.status
200

```

Sounds like the default header in the __http_request method needs to be changed from None to {"Accept":"application/json"}?

**Comment by yuce** [comment]
Hi @gireeshramji, thanks for your issue report. The Getting Started projects currently require Pilosa 0.8, they weren't tested with the 1.x release. Since you are using Pilosa 1.x, you should upgrade the Python `pilosa` library to `1.0.2`. You can do that using: `pip install -U pilosa==1.0.2`. Note that `client.status` method was removed from this version.

**Comment by gireeshramji** [comment]
Thanks @yuce I'll try that and let you know.

**Comment by yuce** [comment]
@gireeshramji We have updated the code in this repo for Pilosa 1.x, so closing this issue. Feel free to reopen it if there are any problems.
